### ISSUE TITLE
The canonicalize-proto-file executable does not build with ghc-9.2

### ISSUE THREAD

**Issue by TristanCacqueray** [awakesecurity/proto3-suite#192]
The build fails with:

```
Building executable 'canonicalize-proto-file' for proto3-suite-0.5.0..
[1 of 1] Compiling Main             ( tools/canonicalize-proto-file/Main.hs, dist/build/canonicalize-proto-file/canonicalize-proto-file-tmp/Main.o )

tools/canonicalize-proto-file/Main.hs:20:61: error:
    Module ‘Data.Semigroup’ does not export ‘Option(..)’
   |
20 | import           Data.Semigroup                   (Min(..), Option(..))
```

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/awakesecurity/proto3-suite/pull/193

**Comment by TristanCacqueray** [comment]
For what its worth, I'm testing the PRs for ghc-9.2 in this nixpkgs overlay: https://github.com/change-metrics/monocle/pull/864 . And with #193, proto3-suite now builds. Thanks!

**Comment by Gabriel439** [comment]
You're welcome!

**Comment by riz0id** [comment]
Support for GHC 9.2.X has been resolved.
